// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { BlockchainRecord } from "./blockchain_record_type";
import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `blockchain_record`.
 *
 * Obtain a handle from the [`blockchainRecord`] property on [`RemoteTables`],
 * like `ctx.db.blockchainRecord`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.blockchainRecord.on_insert(...)`.
 */
export class BlockchainRecordTableHandle {
  tableCache: TableCache<BlockchainRecord>;

  constructor(tableCache: TableCache<BlockchainRecord>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<BlockchainRecord> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `recordId` unique index on the table `blockchain_record`,
   * which allows point queries on the field of the same name
   * via the [`BlockchainRecordRecordIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.blockchainRecord.recordId().find(...)`.
   *
   * Get a handle on the `recordId` unique index on the table `blockchain_record`.
   */
  recordId = {
    // Find the subscribed row whose `recordId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): BlockchainRecord | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.recordId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: BlockchainRecord) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: BlockchainRecord) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: BlockchainRecord) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: BlockchainRecord) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: BlockchainRecord, newRow: BlockchainRecord) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: BlockchainRecord, newRow: BlockchainRecord) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
