// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type BlockchainRecord = {
  recordId: bigint,
  applicationId: bigint,
  txHash: string,
  network: string,
  recordedAt: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace BlockchainRecord {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("recordId", AlgebraicType.createU64Type()),
      new ProductTypeElement("applicationId", AlgebraicType.createU64Type()),
      new ProductTypeElement("txHash", AlgebraicType.createStringType()),
      new ProductTypeElement("network", AlgebraicType.createStringType()),
      new ProductTypeElement("recordedAt", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: BlockchainRecord): void {
    BlockchainRecord.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): BlockchainRecord {
    return BlockchainRecord.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


