// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { CollaborationSession } from "./collaboration_session_type";
import { CollabStatus as __CollabStatus } from "./collab_status_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `collab_session`.
 *
 * Obtain a handle from the [`collabSession`] property on [`RemoteTables`],
 * like `ctx.db.collabSession`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.collabSession.on_insert(...)`.
 */
export class CollabSessionTableHandle {
  tableCache: TableCache<CollaborationSession>;

  constructor(tableCache: TableCache<CollaborationSession>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<CollaborationSession> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `sessionId` unique index on the table `collab_session`,
   * which allows point queries on the field of the same name
   * via the [`CollabSessionSessionIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.collabSession.sessionId().find(...)`.
   *
   * Get a handle on the `sessionId` unique index on the table `collab_session`.
   */
  sessionId = {
    // Find the subscribed row whose `sessionId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): CollaborationSession | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.sessionId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: CollaborationSession) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: CollaborationSession) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: CollaborationSession) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: CollaborationSession) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: CollaborationSession, newRow: CollaborationSession) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: CollaborationSession, newRow: CollaborationSession) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
