// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { CollabStatus as __CollabStatus } from "./collab_status_type";

export type CollaborationSession = {
  sessionId: bigint,
  title: string,
  createdBy: Identity,
  status: __CollabStatus,
  startedAt: Timestamp,
  endedAt: Timestamp,
  ended: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace CollaborationSession {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("sessionId", AlgebraicType.createU64Type()),
      new ProductTypeElement("title", AlgebraicType.createStringType()),
      new ProductTypeElement("createdBy", AlgebraicType.createIdentityType()),
      new ProductTypeElement("status", __CollabStatus.getTypeScriptAlgebraicType()),
      new ProductTypeElement("startedAt", AlgebraicType.createTimestampType()),
      new ProductTypeElement("endedAt", AlgebraicType.createTimestampType()),
      new ProductTypeElement("ended", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: CollaborationSession): void {
    CollaborationSession.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): CollaborationSession {
    return CollaborationSession.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


