// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { DocumentGeneration } from "./document_generation_type";
import { DocType as __DocType } from "./doc_type_type";
import { DocGenStatus as __DocGenStatus } from "./doc_gen_status_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `document_generation`.
 *
 * Obtain a handle from the [`documentGeneration`] property on [`RemoteTables`],
 * like `ctx.db.documentGeneration`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.documentGeneration.on_insert(...)`.
 */
export class DocumentGenerationTableHandle {
  tableCache: TableCache<DocumentGeneration>;

  constructor(tableCache: TableCache<DocumentGeneration>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<DocumentGeneration> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `docId` unique index on the table `document_generation`,
   * which allows point queries on the field of the same name
   * via the [`DocumentGenerationDocIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.documentGeneration.docId().find(...)`.
   *
   * Get a handle on the `docId` unique index on the table `document_generation`.
   */
  docId = {
    // Find the subscribed row whose `docId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): DocumentGeneration | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.docId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: DocumentGeneration) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: DocumentGeneration) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: DocumentGeneration) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: DocumentGeneration) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: DocumentGeneration, newRow: DocumentGeneration) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: DocumentGeneration, newRow: DocumentGeneration) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
