// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { AlertSeverity as __AlertSeverity } from "./alert_severity_type";

export type InfringementAlert = {
  alertId: bigint,
  applicationId: bigint,
  alertType: string,
  severity: __AlertSeverity,
  description: string,
  detectedAt: Timestamp,
  resolved: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace InfringementAlert {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("alertId", AlgebraicType.createU64Type()),
      new ProductTypeElement("applicationId", AlgebraicType.createU64Type()),
      new ProductTypeElement("alertType", AlgebraicType.createStringType()),
      new ProductTypeElement("severity", __AlertSeverity.getTypeScriptAlgebraicType()),
      new ProductTypeElement("description", AlgebraicType.createStringType()),
      new ProductTypeElement("detectedAt", AlgebraicType.createTimestampType()),
      new ProductTypeElement("resolved", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: InfringementAlert): void {
    InfringementAlert.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): InfringementAlert {
    return InfringementAlert.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


