// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { InventorConnection } from "./inventor_connection_type";
import { ConnectionStatus as __ConnectionStatus } from "./connection_status_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `inventor_connection`.
 *
 * Obtain a handle from the [`inventorConnection`] property on [`RemoteTables`],
 * like `ctx.db.inventorConnection`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.inventorConnection.on_insert(...)`.
 */
export class InventorConnectionTableHandle {
  tableCache: TableCache<InventorConnection>;

  constructor(tableCache: TableCache<InventorConnection>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<InventorConnection> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `connectionId` unique index on the table `inventor_connection`,
   * which allows point queries on the field of the same name
   * via the [`InventorConnectionConnectionIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.inventorConnection.connectionId().find(...)`.
   *
   * Get a handle on the `connectionId` unique index on the table `inventor_connection`.
   */
  connectionId = {
    // Find the subscribed row whose `connectionId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): InventorConnection | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.connectionId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: InventorConnection) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: InventorConnection) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: InventorConnection) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: InventorConnection) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: InventorConnection, newRow: InventorConnection) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: InventorConnection, newRow: InventorConnection) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
