// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type InventorProfile = {
  identity: Identity,
  name: string,
  email: string,
  affiliation: string,
  skills: string,
  bio: string,
  createdAt: Timestamp,
  updatedAt: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace InventorProfile {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("identity", AlgebraicType.createIdentityType()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("email", AlgebraicType.createStringType()),
      new ProductTypeElement("affiliation", AlgebraicType.createStringType()),
      new ProductTypeElement("skills", AlgebraicType.createStringType()),
      new ProductTypeElement("bio", AlgebraicType.createStringType()),
      new ProductTypeElement("createdAt", AlgebraicType.createTimestampType()),
      new ProductTypeElement("updatedAt", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: InventorProfile): void {
    InventorProfile.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): InventorProfile {
    return InventorProfile.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


