// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { ConnectionStatus as __ConnectionStatus } from "./connection_status_type";

export type InventorConnection = {
  connectionId: bigint,
  a: Identity,
  b: Identity,
  status: __ConnectionStatus,
  createdAt: Timestamp,
  updatedAt: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace InventorConnection {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("connectionId", AlgebraicType.createU64Type()),
      new ProductTypeElement("a", AlgebraicType.createIdentityType()),
      new ProductTypeElement("b", AlgebraicType.createIdentityType()),
      new ProductTypeElement("status", __ConnectionStatus.getTypeScriptAlgebraicType()),
      new ProductTypeElement("createdAt", AlgebraicType.createTimestampType()),
      new ProductTypeElement("updatedAt", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: InventorConnection): void {
    InventorConnection.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): InventorConnection {
    return InventorConnection.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


