// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { TrendMetric as __TrendMetric } from "./trend_metric_type";

export type MarketTrendSnapshot = {
  snapshotId: bigint,
  segment: string,
  metric: __TrendMetric,
  value: number,
  window: string,
  computedAt: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace MarketTrendSnapshot {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("snapshotId", AlgebraicType.createU64Type()),
      new ProductTypeElement("segment", AlgebraicType.createStringType()),
      new ProductTypeElement("metric", __TrendMetric.getTypeScriptAlgebraicType()),
      new ProductTypeElement("value", AlgebraicType.createF64Type()),
      new ProductTypeElement("window", AlgebraicType.createStringType()),
      new ProductTypeElement("computedAt", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: MarketTrendSnapshot): void {
    MarketTrendSnapshot.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): MarketTrendSnapshot {
    return MarketTrendSnapshot.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


