// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { MarketTrendSnapshot } from "./market_trend_snapshot_type";
import { TrendMetric as __TrendMetric } from "./trend_metric_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `market_trend_snapshot`.
 *
 * Obtain a handle from the [`marketTrendSnapshot`] property on [`RemoteTables`],
 * like `ctx.db.marketTrendSnapshot`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.marketTrendSnapshot.on_insert(...)`.
 */
export class MarketTrendSnapshotTableHandle {
  tableCache: TableCache<MarketTrendSnapshot>;

  constructor(tableCache: TableCache<MarketTrendSnapshot>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<MarketTrendSnapshot> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `snapshotId` unique index on the table `market_trend_snapshot`,
   * which allows point queries on the field of the same name
   * via the [`MarketTrendSnapshotSnapshotIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.marketTrendSnapshot.snapshotId().find(...)`.
   *
   * Get a handle on the `snapshotId` unique index on the table `market_trend_snapshot`.
   */
  snapshotId = {
    // Find the subscribed row whose `snapshotId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): MarketTrendSnapshot | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.snapshotId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: MarketTrendSnapshot) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: MarketTrendSnapshot) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: MarketTrendSnapshot) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: MarketTrendSnapshot) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: MarketTrendSnapshot, newRow: MarketTrendSnapshot) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: MarketTrendSnapshot, newRow: MarketTrendSnapshot) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
