// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { PatentStatus as __PatentStatus } from "./patent_status_type";

export type PatentApplication = {
  applicationId: bigint,
  owner: Identity,
  title: string,
  abstractText: string,
  claimsText: string,
  status: __PatentStatus,
  createdAt: Timestamp,
  lastUpdated: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace PatentApplication {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("applicationId", AlgebraicType.createU64Type()),
      new ProductTypeElement("owner", AlgebraicType.createIdentityType()),
      new ProductTypeElement("title", AlgebraicType.createStringType()),
      new ProductTypeElement("abstractText", AlgebraicType.createStringType()),
      new ProductTypeElement("claimsText", AlgebraicType.createStringType()),
      new ProductTypeElement("status", __PatentStatus.getTypeScriptAlgebraicType()),
      new ProductTypeElement("createdAt", AlgebraicType.createTimestampType()),
      new ProductTypeElement("lastUpdated", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: PatentApplication): void {
    PatentApplication.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): PatentApplication {
    return PatentApplication.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


