// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { PatentApplication } from "./patent_application_type";
import { PatentStatus as __PatentStatus } from "./patent_status_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `patent_application`.
 *
 * Obtain a handle from the [`patentApplication`] property on [`RemoteTables`],
 * like `ctx.db.patentApplication`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.patentApplication.on_insert(...)`.
 */
export class PatentApplicationTableHandle {
  tableCache: TableCache<PatentApplication>;

  constructor(tableCache: TableCache<PatentApplication>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<PatentApplication> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `applicationId` unique index on the table `patent_application`,
   * which allows point queries on the field of the same name
   * via the [`PatentApplicationApplicationIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.patentApplication.applicationId().find(...)`.
   *
   * Get a handle on the `applicationId` unique index on the table `patent_application`.
   */
  applicationId = {
    // Find the subscribed row whose `applicationId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): PatentApplication | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.applicationId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: PatentApplication) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: PatentApplication) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: PatentApplication) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: PatentApplication) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: PatentApplication, newRow: PatentApplication) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: PatentApplication, newRow: PatentApplication) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
