// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
// A namespace for generated variants and helper functions.
export namespace PatentStatus {
  // These are the generated variant types for each variant of the tagged union.
  // One type is generated per variant and will be used in the `value` field of
  // the tagged union.
  export type Draft = { tag: "Draft" };
  export type Submitted = { tag: "Submitted" };
  export type Examination = { tag: "Examination" };
  export type Granted = { tag: "Granted" };
  export type Rejected = { tag: "Rejected" };
  export type Abandoned = { tag: "Abandoned" };

  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  export const Draft = { tag: "Draft" };
  export const Submitted = { tag: "Submitted" };
  export const Examination = { tag: "Examination" };
  export const Granted = { tag: "Granted" };
  export const Rejected = { tag: "Rejected" };
  export const Abandoned = { tag: "Abandoned" };

  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createSumType([
      new SumTypeVariant("Draft", AlgebraicType.createProductType([])),
      new SumTypeVariant("Submitted", AlgebraicType.createProductType([])),
      new SumTypeVariant("Examination", AlgebraicType.createProductType([])),
      new SumTypeVariant("Granted", AlgebraicType.createProductType([])),
      new SumTypeVariant("Rejected", AlgebraicType.createProductType([])),
      new SumTypeVariant("Abandoned", AlgebraicType.createProductType([])),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: PatentStatus): void {
      PatentStatus.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): PatentStatus {
      return PatentStatus.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

// The tagged union or sum type for the algebraic type `PatentStatus`.
export type PatentStatus = PatentStatus.Draft | PatentStatus.Submitted | PatentStatus.Examination | PatentStatus.Granted | PatentStatus.Rejected | PatentStatus.Abandoned;

export default PatentStatus;

