// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { PortfolioRole as __PortfolioRole } from "./portfolio_role_type";

export type PatentPortfolioEntry = {
  entryId: bigint,
  owner: Identity,
  applicationId: bigint,
  role: __PortfolioRole,
  addedAt: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace PatentPortfolioEntry {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("entryId", AlgebraicType.createU64Type()),
      new ProductTypeElement("owner", AlgebraicType.createIdentityType()),
      new ProductTypeElement("applicationId", AlgebraicType.createU64Type()),
      new ProductTypeElement("role", __PortfolioRole.getTypeScriptAlgebraicType()),
      new ProductTypeElement("addedAt", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: PatentPortfolioEntry): void {
    PatentPortfolioEntry.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): PatentPortfolioEntry {
    return PatentPortfolioEntry.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


