// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
// A namespace for generated variants and helper functions.
export namespace PortfolioRole {
  // These are the generated variant types for each variant of the tagged union.
  // One type is generated per variant and will be used in the `value` field of
  // the tagged union.
  export type Owner = { tag: "Owner" };
  export type CoOwner = { tag: "CoOwner" };
  export type Licensee = { tag: "Licensee" };
  export type Viewer = { tag: "Viewer" };

  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  export const Owner = { tag: "Owner" };
  export const CoOwner = { tag: "CoOwner" };
  export const Licensee = { tag: "Licensee" };
  export const Viewer = { tag: "Viewer" };

  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createSumType([
      new SumTypeVariant("Owner", AlgebraicType.createProductType([])),
      new SumTypeVariant("CoOwner", AlgebraicType.createProductType([])),
      new SumTypeVariant("Licensee", AlgebraicType.createProductType([])),
      new SumTypeVariant("Viewer", AlgebraicType.createProductType([])),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: PortfolioRole): void {
      PortfolioRole.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): PortfolioRole {
      return PortfolioRole.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

// The tagged union or sum type for the algebraic type `PortfolioRole`.
export type PortfolioRole = PortfolioRole.Owner | PortfolioRole.CoOwner | PortfolioRole.Licensee | PortfolioRole.Viewer;

export default PortfolioRole;

