// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { PatentPortfolioEntry } from "./patent_portfolio_entry_type";
import { PortfolioRole as __PortfolioRole } from "./portfolio_role_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `portfolio_entry`.
 *
 * Obtain a handle from the [`portfolioEntry`] property on [`RemoteTables`],
 * like `ctx.db.portfolioEntry`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.portfolioEntry.on_insert(...)`.
 */
export class PortfolioEntryTableHandle {
  tableCache: TableCache<PatentPortfolioEntry>;

  constructor(tableCache: TableCache<PatentPortfolioEntry>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<PatentPortfolioEntry> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `entryId` unique index on the table `portfolio_entry`,
   * which allows point queries on the field of the same name
   * via the [`PortfolioEntryEntryIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.portfolioEntry.entryId().find(...)`.
   *
   * Get a handle on the `entryId` unique index on the table `portfolio_entry`.
   */
  entryId = {
    // Find the subscribed row whose `entryId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): PatentPortfolioEntry | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.entryId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: PatentPortfolioEntry) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: PatentPortfolioEntry) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: PatentPortfolioEntry) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: PatentPortfolioEntry) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: PatentPortfolioEntry, newRow: PatentPortfolioEntry) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: PatentPortfolioEntry, newRow: PatentPortfolioEntry) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
