// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type SessionParticipant = {
  rowId: bigint,
  sessionId: bigint,
  participant: Identity,
  joinedAt: Timestamp,
  active: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace SessionParticipant {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("rowId", AlgebraicType.createU64Type()),
      new ProductTypeElement("sessionId", AlgebraicType.createU64Type()),
      new ProductTypeElement("participant", AlgebraicType.createIdentityType()),
      new ProductTypeElement("joinedAt", AlgebraicType.createTimestampType()),
      new ProductTypeElement("active", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: SessionParticipant): void {
    SessionParticipant.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): SessionParticipant {
    return SessionParticipant.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


