// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { Stage as __Stage } from "./stage_type";

export type StageProgress = {
  progressId: bigint,
  applicationId: bigint,
  stage: __Stage,
  percent: number,
  updatedAt: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace StageProgress {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("progressId", AlgebraicType.createU64Type()),
      new ProductTypeElement("applicationId", AlgebraicType.createU64Type()),
      new ProductTypeElement("stage", __Stage.getTypeScriptAlgebraicType()),
      new ProductTypeElement("percent", AlgebraicType.createU8Type()),
      new ProductTypeElement("updatedAt", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: StageProgress): void {
    StageProgress.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): StageProgress {
    return StageProgress.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


