// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { StageProgress } from "./stage_progress_type";
import { Stage as __Stage } from "./stage_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `stage_progress`.
 *
 * Obtain a handle from the [`stageProgress`] property on [`RemoteTables`],
 * like `ctx.db.stageProgress`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.stageProgress.on_insert(...)`.
 */
export class StageProgressTableHandle {
  tableCache: TableCache<StageProgress>;

  constructor(tableCache: TableCache<StageProgress>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<StageProgress> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `progressId` unique index on the table `stage_progress`,
   * which allows point queries on the field of the same name
   * via the [`StageProgressProgressIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.stageProgress.progressId().find(...)`.
   *
   * Get a handle on the `progressId` unique index on the table `stage_progress`.
   */
  progressId = {
    // Find the subscribed row whose `progressId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): StageProgress | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.progressId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: StageProgress) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: StageProgress) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: StageProgress) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: StageProgress) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: StageProgress, newRow: StageProgress) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: StageProgress, newRow: StageProgress) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
