// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
// A namespace for generated variants and helper functions.
export namespace TrendMetric {
  // These are the generated variant types for each variant of the tagged union.
  // One type is generated per variant and will be used in the `value` field of
  // the tagged union.
  export type FilingCount = { tag: "FilingCount" };
  export type GrantCount = { tag: "GrantCount" };
  export type AlertCount = { tag: "AlertCount" };
  export type ActiveSessionCount = { tag: "ActiveSessionCount" };

  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  export const FilingCount = { tag: "FilingCount" };
  export const GrantCount = { tag: "GrantCount" };
  export const AlertCount = { tag: "AlertCount" };
  export const ActiveSessionCount = { tag: "ActiveSessionCount" };

  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createSumType([
      new SumTypeVariant("FilingCount", AlgebraicType.createProductType([])),
      new SumTypeVariant("GrantCount", AlgebraicType.createProductType([])),
      new SumTypeVariant("AlertCount", AlgebraicType.createProductType([])),
      new SumTypeVariant("ActiveSessionCount", AlgebraicType.createProductType([])),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: TrendMetric): void {
      TrendMetric.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): TrendMetric {
      return TrendMetric.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

// The tagged union or sum type for the algebraic type `TrendMetric`.
export type TrendMetric = TrendMetric.FilingCount | TrendMetric.GrantCount | TrendMetric.AlertCount | TrendMetric.ActiveSessionCount;

export default TrendMetric;

