// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

import { DocType as __DocType } from "./doc_type_type";
import { DocGenStatus as __DocGenStatus } from "./doc_gen_status_type";

export type UpsertDocumentGeneration = {
  applicationId: bigint,
  docType: __DocType,
  status: __DocGenStatus,
  errorMessage: string,
};

/**
 * A namespace for generated helper functions.
 */
export namespace UpsertDocumentGeneration {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("applicationId", AlgebraicType.createU64Type()),
      new ProductTypeElement("docType", __DocType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("status", __DocGenStatus.getTypeScriptAlgebraicType()),
      new ProductTypeElement("errorMessage", AlgebraicType.createStringType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: UpsertDocumentGeneration): void {
    UpsertDocumentGeneration.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): UpsertDocumentGeneration {
    return UpsertDocumentGeneration.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

